[programs.mainnet]
nanox_ico_dao = "RNGF2q87ouXMQGTxgcFPrxdUC2SFTx9HoBvhCSfpuUd"

[programs.devnet]
onering_finance = "RNGF2q87ouXMQGTxgcFPrxdUC2SFTx9HoBvhCSfpuUd"

[programs.localnet]
onering_finance = "RNGF2q87ouXMQGTxgcFPrxdUC2SFTx9HoBvhCSfpuUd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"
